import type { EmergencyCategory, FacilityType, Specialty, SymptomCode, Urgency } from '@sanjeevani/types';
import type { Localized } from './localized';

export const SYMPTOM_LABELS: Record<SymptomCode, Localized> = {
  fever: { en: 'fever', hi: 'बुखार', hinglish: 'bukhar' },
  chills: { en: 'chills', hi: 'कंपकंपी', hinglish: 'kapkapi' },
  body_ache: { en: 'body ache', hi: 'बदन दर्द', hinglish: 'badan dard' },
  fatigue: { en: 'tiredness', hi: 'थकान', hinglish: 'thakan' },
  headache: { en: 'headache', hi: 'सिर दर्द', hinglish: 'sir dard' },
  cough: { en: 'cough', hi: 'खांसी', hinglish: 'khansi' },
  sore_throat: { en: 'sore throat', hi: 'गले में दर्द', hinglish: 'gale mein dard' },
  runny_nose: { en: 'cold or runny nose', hi: 'जुकाम', hinglish: 'zukam' },
  breathlessness: { en: 'breathlessness', hi: 'सांस फूलना', hinglish: 'saans phoolna' },
  wheezing: { en: 'wheezing', hi: 'सांस में सीटी', hinglish: 'saans mein seeti' },
  chest_pain: { en: 'chest pain', hi: 'सीने में दर्द', hinglish: 'seene mein dard' },
  palpitations: { en: 'racing heartbeat', hi: 'तेज़ धड़कन', hinglish: 'tez dhadkan' },
  abdominal_pain: { en: 'stomach pain', hi: 'पेट दर्द', hinglish: 'pet dard' },
  nausea: { en: 'nausea', hi: 'जी मचलना', hinglish: 'ji machalna' },
  vomiting: { en: 'vomiting', hi: 'उल्टी', hinglish: 'ulti' },
  diarrhea: { en: 'loose motions', hi: 'दस्त', hinglish: 'dast' },
  constipation: { en: 'constipation', hi: 'कब्ज़', hinglish: 'kabz' },
  loss_of_appetite: { en: 'low appetite', hi: 'भूख न लगना', hinglish: 'bhookh na lagna' },
  dizziness: { en: 'dizziness', hi: 'चक्कर', hinglish: 'chakkar' },
  fainting: { en: 'fainting', hi: 'बेहोशी', hinglish: 'behoshi' },
  weakness: { en: 'weakness', hi: 'कमज़ोरी', hinglish: 'kamzori' },
  numbness: { en: 'numbness', hi: 'सुन्नपन', hinglish: 'sunnpan' },
  confusion: { en: 'confusion', hi: 'भ्रम', hinglish: 'confusion' },
  seizure: { en: 'seizure', hi: 'दौरा', hinglish: 'daura' },
  rash: { en: 'rash', hi: 'दाने', hinglish: 'daane' },
  itching: { en: 'itching', hi: 'खुजली', hinglish: 'khujli' },
  swelling: { en: 'swelling', hi: 'सूजन', hinglish: 'soojan' },
  ear_pain: { en: 'ear pain', hi: 'कान दर्द', hinglish: 'kaan dard' },
  eye_pain: { en: 'eye pain', hi: 'आंख में दर्द', hinglish: 'aankh mein dard' },
  eye_redness: { en: 'red eyes', hi: 'लाल आंखें', hinglish: 'laal aankhen' },
  blurred_vision: { en: 'blurred vision', hi: 'धुंधला दिखना', hinglish: 'dhundhla dikhna' },
  toothache: { en: 'toothache', hi: 'दांत दर्द', hinglish: 'daant dard' },
  back_pain: { en: 'back pain', hi: 'कमर दर्द', hinglish: 'kamar dard' },
  joint_pain: { en: 'joint pain', hi: 'जोड़ों में दर्द', hinglish: 'jodon mein dard' },
  neck_stiffness: { en: 'stiff neck', hi: 'गर्दन में अकड़न', hinglish: 'gardan mein akdan' },
  injury: { en: 'injury', hi: 'चोट', hinglish: 'chot' },
  burn: { en: 'burn', hi: 'जलना', hinglish: 'jalna' },
  bleeding: { en: 'bleeding', hi: 'खून आना', hinglish: 'khoon aana' },
  painful_urination: { en: 'burning urine', hi: 'पेशाब में जलन', hinglish: 'peshab mein jalan' },
  blood_in_urine: { en: 'blood in urine', hi: 'पेशाब में खून', hinglish: 'peshab mein khoon' },
  blood_in_stool: { en: 'blood in stool', hi: 'मल में खून', hinglish: 'mal mein khoon' },
  blood_in_vomit: { en: 'vomiting blood', hi: 'खून की उल्टी', hinglish: 'khoon ki ulti' },
  dehydration: { en: 'signs of dehydration', hi: 'पानी की कमी', hinglish: 'paani ki kami' },
  animal_bite: { en: 'animal bite', hi: 'जानवर का काटना', hinglish: 'jaanwar ka kaatna' },
  pregnancy_concern: { en: 'pregnancy concern', hi: 'गर्भावस्था से जुड़ी चिंता', hinglish: 'pregnancy se judi chinta' },
  anxiety: { en: 'anxiety', hi: 'बेचैनी', hinglish: 'bechaini' },
  low_mood: { en: 'low mood', hi: 'उदासी', hinglish: 'udaasi' },
  insomnia: { en: 'trouble sleeping', hi: 'नींद न आना', hinglish: 'neend na aana' },
};

export const SPECIALTY_LABELS: Record<Specialty, Localized> = {
  emergency_medicine: { en: 'Emergency', hi: 'इमरजेंसी', hinglish: 'Emergency' },
  general_medicine: { en: 'General Medicine', hi: 'जनरल मेडिसिन', hinglish: 'General Medicine' },
  pediatrics: { en: 'Paediatrics', hi: 'शिशु रोग', hinglish: 'Bachchon ke doctor' },
  cardiology: { en: 'Cardiology', hi: 'हृदय रोग', hinglish: 'Cardiology' },
  neurology: { en: 'Neurology', hi: 'न्यूरोलॉजी', hinglish: 'Neurology' },
  pulmonology: { en: 'Pulmonology', hi: 'फेफड़ा रोग', hinglish: 'Pulmonology' },
  gastroenterology: { en: 'Gastroenterology', hi: 'पेट रोग', hinglish: 'Gastroenterology' },
  orthopedics: { en: 'Orthopaedics', hi: 'हड्डी रोग', hinglish: 'Haddi ke doctor' },
  ent: { en: 'ENT', hi: 'नाक-कान-गला', hinglish: 'ENT' },
  ophthalmology: { en: 'Eye care', hi: 'नेत्र रोग', hinglish: 'Aankh ke doctor' },
  dermatology: { en: 'Dermatology', hi: 'त्वचा रोग', hinglish: 'Skin ke doctor' },
  obstetrics_gynecology: { en: 'Obstetrics & Gynaecology', hi: 'स्त्री एवं प्रसूति रोग', hinglish: 'Gynaecology' },
  dental: { en: 'Dental', hi: 'दंत रोग', hinglish: 'Dentist' },
  psychiatry: { en: 'Mental health', hi: 'मानसिक स्वास्थ्य', hinglish: 'Mental health' },
  urology: { en: 'Urology', hi: 'मूत्र रोग', hinglish: 'Urology' },
};

export const FACILITY_TYPE_LABELS: Record<FacilityType, Localized> = {
  emergency_department: { en: 'emergency department', hi: 'इमरजेंसी विभाग', hinglish: 'emergency department' },
  hospital: { en: 'hospital', hi: 'अस्पताल', hinglish: 'hospital' },
  clinic: { en: 'clinic', hi: 'क्लिनिक', hinglish: 'clinic' },
  pharmacy: { en: 'pharmacy', hi: 'दवा की दुकान', hinglish: 'medical store' },
  diagnostic_lab: { en: 'diagnostic lab', hi: 'जांच केंद्र', hinglish: 'lab' },
};

export const URGENCY_LABELS: Record<Urgency, Localized> = {
  self_care: { en: 'Home care', hi: 'घर पर देखभाल', hinglish: 'Ghar par dekhbhal' },
  routine: { en: 'See a doctor soon', hi: 'जल्द डॉक्टर को दिखाएं', hinglish: 'Jaldi doctor ko dikhayein' },
  urgent: { en: 'See a doctor today', hi: 'आज ही डॉक्टर को दिखाएं', hinglish: 'Aaj hi doctor ko dikhayein' },
  emergency: { en: 'Emergency', hi: 'इमरजेंसी', hinglish: 'Emergency' },
};

export const EMERGENCY_CATEGORY_LABELS: Record<EmergencyCategory, Localized> = {
  cardiac: { en: 'Possible heart emergency', hi: 'दिल से जुड़ी संभावित इमरजेंसी', hinglish: 'Dil se judi emergency ho sakti hai' },
  breathing: { en: 'Serious breathing difficulty', hi: 'सांस लेने में गंभीर दिक्कत', hinglish: 'Saans lene mein gambhir dikkat' },
  stroke: { en: 'Possible stroke signs', hi: 'स्ट्रोक (लकवा) के संभावित लक्षण', hinglish: 'Stroke (lakwa) ke lakshan ho sakte hain' },
  unconscious: { en: 'Person not responding', hi: 'व्यक्ति होश में नहीं है', hinglish: 'Vyakti hosh mein nahi hai' },
  major_trauma: { en: 'Serious injury', hi: 'गंभीर चोट', hinglish: 'Gambhir chot' },
  severe_bleeding: { en: 'Heavy bleeding', hi: 'बहुत ज़्यादा खून बहना', hinglish: 'Bahut zyada khoon behna' },
  seizure: { en: 'Seizure', hi: 'दौरा', hinglish: 'Daura (seizure)' },
  anaphylaxis: { en: 'Severe allergic reaction', hi: 'गंभीर एलर्जी', hinglish: 'Gambhir allergy' },
  poisoning: { en: 'Possible poisoning', hi: 'संभावित ज़हर', hinglish: 'Zeher ka khatra' },
  self_harm: { en: 'You deserve support right now', hi: 'आपको अभी सहारा मिलना चाहिए', hinglish: 'Aapko abhi sahara milna chahiye' },
  severe_burn: { en: 'Serious burn', hi: 'गंभीर जलन', hinglish: 'Gambhir jalan' },
  obstetric: { en: 'Pregnancy emergency', hi: 'गर्भावस्था इमरजेंसी', hinglish: 'Pregnancy emergency' },
  infant_danger: { en: 'Baby needs urgent care', hi: 'शिशु को तुरंत इलाज चाहिए', hinglish: 'Baby ko turant ilaaj chahiye' },
  meningitis_signs: { en: 'Fever with danger signs', hi: 'खतरे के लक्षणों के साथ बुखार', hinglish: 'Khatre ke lakshanon ke saath bukhar' },
  user_requested: { en: 'Emergency help', hi: 'इमरजेंसी मदद', hinglish: 'Emergency madad' },
};
